{{- if and .Values.config.postgres.host .Values.config.postgres.username .Values.config.postgres.password .Values.config.postgres.dbname }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-staking-synchronizer.postgresSecretName" . }}
type: Opaque
data:
  host: {{ .Values.config.postgres.host | b64enc }}
  username: {{ .Values.config.postgres.username | b64enc }}
  password: {{ .Values.config.postgres.password | b64enc }}
  dbname: {{ .Values.config.postgres.dbname | b64enc }}

---
{{- end }}
{{- if .Values.config.postgres.dbLocations }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-staking-synchronizer.dbLocationsSecretName" . }}
type: Opaque
data:
  dbLocations: {{ .Values.config.postgres.dbLocations | b64enc }}

---
{{- end }}
{{- if .Values.config.substrateMnemonic }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-staking-synchronizer.substrateMnemonicSecretName" . }}
type: Opaque
data:
  substrateMnemonic: {{ .Values.config.substrateMnemonic | b64enc }}

---
{{- end }}
{{- if .Values.config.bucketname }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-staking-synchronizer.bucketnameSecretName" . }}
type: Opaque
data:
  bucketname: {{ .Values.config.bucketname | b64enc }}

---
{{- end }}
{{- if .Values.config.storageBaseURI }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-staking-synchronizer.storageBaseURISecretName" . }}
type: Opaque
data:
  storageBaseURI: {{ .Values.config.storageBaseURI | b64enc }}

{{- end }}

