apiVersion: v1
kind: Secret
metadata:
    name: {{ include "debio-app-deployer.secretName" . }}
data:
  {{- if .Values.config.secrets -}}
  {{- range $line := splitList "\n" .Values.config.secrets -}}
  {{- $parts := regexSplit "=" . 2  }}
  {{ index $parts 0  }}: {{ index $parts 1 | b64enc }}
  {{- end -}}
  {{- end -}}