{{- range .Values.config.nodes }}
{{- if .sessionInjectionEnabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "debio-node.sessionInjectionJobName" $ }}-{{ .name }}
spec:
  backoffLimit: 120
  template:
    spec:
      serviceAccountName: {{ include "debio-node.serviceAccountName" $ }}-{{ .name }}
      containers:
        - name: {{ include "debio-node.sessionInjectionJobName" $ }}
          image: bitnami/kubectl:latest
          command:
            - ./scripts/inject_session_keys.sh
            - {{ include "debio-node.fullname" $ }}-{{ .name }}-0.{{ include "debio-node.fullname" $ }}-{{ .name }}.{{ $.Release.Namespace }}.svc.cluster.local:9933
            - {{ include "debio-node.fullname" $ }}-{{ .name }}
          volumeMounts:
            - name: session-keys
              mountPath: /keys
            - name: key-seed
              mountPath: /key-seed
            - name: scripts
              mountPath: /scripts
      restartPolicy: Never
      volumes:
        - name: session-keys
          secret:
            secretName: {{ include "debio-node.sessionKeySecretName" $ }}-{{ .name }}
            items:
              - key: grandpa
                path: grandpa
              - key: babe
                path: babe
              - key: imonline
                path: imonline
              - key: beefy
                path: beefy
        - name: key-seed
          secret:
            secretName: {{ include "debio-node.sessionKeySecretName" $ }}-{{ .name }}
            items:
              - key: keySeed
                path: key-seed
        - name: scripts
          configMap:
            defaultMode: 0777
            name: {{ include "debio-node.sessionInjectionJobName" $ }}

---

{{- end }}
{{- end }}
