{{- if .Values.serviceAccount.create -}}
{{- range .Values.config.nodes }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "debio-node.serviceAccountName" $ }}-{{ .name }}
  labels:
    {{- include "debio-node.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "debio-node.serviceAccountName" $ }}-{{ .name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "debio-node.serviceAccountName" $ }}-{{ .name }}

---

{{- end }}
{{- end }}
