{{- range .Values.config.nodes }}
{{- if and .keys.private .keys.public }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-node.nodeKeySecretName" $ }}-{{ .name }}
type: Opaque
data:
  private: {{ .keys.private | b64enc }}
  public: {{ .keys.public | b64enc }}

---

{{- end }}
{{- if .sessionKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-node.sessionKeySecretName" $ }}-{{ .name }}
type: Opaque
data:
  keySeed: {{ .sessionKeys.keySeed | b64enc }}
  grandpa: {{ .sessionKeys.grandpa | b64enc }}
  babe: {{ .sessionKeys.babe | b64enc }}
  imonline: {{ .sessionKeys.imonline | b64enc }}
  beefy: {{ .sessionKeys.beefy | b64enc }}

---

{{- end }}
{{- end }}
