{{- if .Values.serviceAccount.create -}}
{{- range .Values.config.nodes }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "debio-node.serviceAccountName" $ }}-{{ .name }}
  labels:
    {{- include "debio-node.labels" $ | nindent 4 }}
  {{- with $.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---

{{- end }}
{{- end }}
