{{- if .Values.config.redis.password }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-conversion.redisSecretName" . }}
type: Opaque
data:
  password: {{ .Values.config.redis.password | b64enc }}

---
{{- end }}
{{- if .Values.config.coinMarketCap.apiKey }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-conversion.coinMarketCapSecretName" . }}
type: Opaque
data:
  apiKey: {{ .Values.config.coinMarketCap.apiKey | b64enc }}

{{- end }}
