apiVersion: v1
kind: Service
metadata:
  name: {{ include "debio-conversion.fullname" . }}
  labels:
    {{- include "debio-conversion.labels" . | nindent 4 }}
    group: debio-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "debio-conversion.selectorLabels" . | nindent 4 }}
