{{- if .Values.config.recaptchaSiteKey }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-customer-ui.recaptchaSiteKeySecretName" . }}
type: Opaque
data:
  recaptchaSiteKey: {{ .Values.config.recaptchaSiteKey | b64enc }}

---
{{- end }}
{{- if .Values.config.debioEscrowETHAddress }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-customer-ui.debioEscrowETHAddressSecretName" . }}
type: Opaque
data:
  debioEscrowETHAddress: {{ .Values.config.debioEscrowETHAddress | b64enc }}

---
{{- end }}
{{- if .Values.config.devDebioEscrowETHAddress }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-customer-ui.devDebioEscrowETHAddressSecretName" . }}
type: Opaque
data:
  devDebioEscrowETHAddress: {{ .Values.config.devDebioEscrowETHAddress | b64enc }}

---
{{- end }}
{{- if .Values.config.daiContractAddress }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-customer-ui.daiContractAddressSecretName" . }}
type: Opaque
data:
  daiContractAddress: {{ .Values.config.daiContractAddress | b64enc }}

---
{{- end }}
{{- if .Values.config.debioApiKey }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debio-customer-ui.debioApiKeySecretName" . }}
type: Opaque
data:
  debioApiKey: {{ .Values.config.debioApiKey | b64enc }}

{{- end }}