apiVersion: v1
kind: Service
metadata:
  name: {{ include "debio-background-worker.fullname" . }}
  labels:
    {{- include "debio-background-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "debio-background-worker.selectorLabels" . | nindent 4 }}
